# deploy mongodb and flask together
version: "3.7"
services:
  web_dev:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/justasklah
    container_name: "justasklah-backend"
    links:
      - mongodb
    environment:
      - ENV=development
      - PORT=5000
      - DB=mongodb://mongodb:27017/justasklah
  mongodb:
    image: mongo:latest
    container_name: "justasklah-db"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null # --quiet

networks:
  default:
    name: web_dev
